# Generated by Django 3.0.3 on 2020-03-29 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_account', '0003_auto_20200327_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='point',
        ),
    ]
