# Generated by Django 3.0.3 on 2020-03-17 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_question', '0003_auto_20200317_1310'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='answer',
            table='answer',
        ),
        migrations.AlterModelTable(
            name='like',
            table='question_like',
        ),
        migrations.AlterModelTable(
            name='question',
            table='question',
        ),
        migrations.AlterModelTable(
            name='questionimage',
            table='question_image',
        ),
    ]
