# Generated by Django 3.0.3 on 2020-03-21 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_question', '0005_auto_20200320_1244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionimage',
            old_name='image',
            new_name='image_url',
        ),
    ]
